# Generated by Django 5.0.1 on 2024-01-31 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='Blog.blog'),
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
