# Generated by Django 5.0.1 on 2024-02-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_content_alter_blogcontent_blog_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
