# Generated by Django 5.0.1 on 2024-02-01 16:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='link_content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogLink',
        ),
        migrations.DeleteModel(
            name='BlogContent',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
