# Generated by Django 5.0.1 on 2024-02-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_blogcontent_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
