# Generated by Django 5.0.1 on 2024-02-01 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
    ]
